### ISSUE TITLE
System Error: The Code execution cannot proceed because msys-2.0.dll was not found

### ISSUE THREAD

**Issue by YaketyJoe** [DarkMatterCore/sbn64#2]
Hola!

I get the "System Error: The Code execution cannot proceed because msys-2.0.dll was not found" when trying to run this. Using latest, but I see that your latest release says that msys dependency was removed. Maybe it is still depending on it.

Windows 10.

Saludos,
-Joseph

**Comment by DarkMatterCore** [comment]
Hi there. Thanks for reporting this issue.

The problem was related to my build environment. It was using the gcc binary from my msys installation instead of the one from TDM-GCC. Sorry about that.

Please test the attached binary and let me know if it works. I'll make a new release if it does.

[sbn64_t1_20200208.zip](https://github.com/DarkMatterCore/sbn64/files/4175570/sbn64_t1_20200208.zip)

**Comment by YaketyJoe** [comment]
This version runs successfully without the mysys error. 

Gracias!

**Comment by DarkMatterCore** [comment]
Thank you for reporting the problem in the first place. :)

I have already pushed the necessary changes and made a new release.
